### ISSUE TITLE
Unable to open licensekey.dat, falling back to limited functionality

### ISSUE THREAD

**Issue by 201508876PMH** [ertagh/teamspeak3-server-arm#16]
First of all, thank you for the amazing docker image! Was exactly what i was looking for ;) 

I decided to throw my ts3 server on my RPI3 instead of my old server. I had a docker image running on my main server, where i copied over the necessary files to my pi...However every time i try to run your rpi docker image, i get the following: 
` |Unable to open licensekey.dat, falling back to limited functionality` 

![rpi-error](https://user-images.githubusercontent.com/42763743/112218920-a206d480-8c24-11eb-8431-a01c53980241.PNG)

**Comment by ertagh** [comment]
I guess you got a linceskey.dat file you want to use?

I never implemented that feature, because no one requested it and I am unable to test it. Didn't want to add a feature that should work..maybe..maybe not.

So, if you need the feature I will make it happen.

**Comment by 201508876PMH** [comment]
Exactly the problem, i have a paid license that i'd like to use. If you'd care to make it, i'd be thrilled! 💯

**Comment by ertagh** [comment]
Pushed an update that hopefully will work..
Please test it and report back

Edit: Just as a note.. the licensekey.dat has to be called like that and has to be inside the "save" directory. After a (re)start of the container it should get picked up and work..

**Comment by 201508876PMH** [comment]
And as simply as that...it works! Thank you for taking the time to help me 🥇 

![rpi-succes](https://user-images.githubusercontent.com/42763743/112360570-c0c3a480-8cd2-11eb-8666-71188e9f6a2f.PNG)

Would you have any suggestions to what image i should pull for the fastest booting TS? :) or simply what to do for faster boots. ATM a reboot takes around 2min for ts to restart :)

**Comment by ertagh** [comment]
Well, the boot actually takes that long because qemu has to initialize and it just runs on one core.
I know that this completely sucks but there is nothing I can do..

Box86 is so much faster but any filetransfer will result in a crash.. Still want to contact the guys over at Box86 to figure out what is going on but my time was somewhat limited.

Long story short: There is nothing out there that I'm aware of for faster booting AND all features..

Edit: Also note that the Box86-container doen't have all updates like qemu does. For example the update for the licensekey file was only for qemu. That's because these containers are not that popular and with the "no fileupload" error.. So I don't really want to promote it that much..

**Comment by 201508876PMH** [comment]
Thank you for the detailed answer 👍 , i'll have a look into it 😃

**Comment by SoraKasvgano** [comment]
@ertagh 
hi ertagh sorry for @ 
maybe we can join box86 's devs Discord to give him a feed back about 30033 crash?
https://discord.gg/6jPVJJdqtu

**Comment by SoraKasvgano** [comment]
@ertagh good news, box 86 owner has fixed the upload file crash bug....after i mentioned
![QQ图片20210328214648](https://user-images.githubusercontent.com/8521327/112754682-c6412780-900f-11eb-993e-ae3b4b29865a.png)

**Comment by ertagh** [comment]
Big thanks for your report and your effort!

I will test and rework the container tomorrow and then update it!

**Comment by ertagh** [comment]
A few days ago I updated the Box86 image and gave it a try. All seems to work now!
I also updated the readme and brought all updates from QEMU to Box86 (like use of a licensekey.dat file)!

You all may consider switching to Box86!
