### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by pibrei** [ertagh/teamspeak3-server-arm#46]
Could anyone tell me step by step how to install it on my ARM64 server? I already have docker installed.

**Comment by ertagh** [comment]
Sure!

1. Create a directory where all the files of the container will be put in
2. Copy the run example for `:latest-box`
3. Within the run example replace `{path}` with the path to the directory you created in step 1
4. Within the run example replace the time zone to yours
5. Run the altered run command

If this fails (e.g. container shuts down), you may try your luck with the `:latest` tag instead of `:latest-box`.
The steps above are all also valid for this tag too.
